services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/api/v1}
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/api/v1}
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SERVER_PORT: ${SERVER_PORT:-8080}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    restart: on-failure
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    env_file:
      - ./backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-meu_projeto}
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
