#spring.data.mongodb.uri=mongodb://admin:vibe_password@127.0.0.1:27017/guaxispace_db?authSource=admin
# Força o Spring a não tentar adivinhar nada além da URI acima
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy
